export enum ElevenLabsSupportedLanguages {
  english = 'english',
  japanese = 'japanese',
  chinese = 'chinese',
  german = 'german',
  hindi = 'hindi',
  french = 'french',
  korean = 'korean',
  portuguese = 'portuguese',
  italian = 'italian',
  spanish = 'spanish',
  indonesian = 'indonesian',
  dutch = 'dutch',
  turkish = 'turkish',
  filipino = 'filipino',
  polish = 'polish',
  swedish = 'swedish',
  bulgarian = 'bulgarian',
  romanian = 'romanian',
  arabic = 'arabic',
  czech = 'czech',
  greek = 'greek',
  finnish = 'finnish',
  croatin = 'croatin',
  malay = 'malay',
  slovak = 'slovak',
  danish = 'danish',
  tamil = 'tamil',
  ukrainian = 'ukrainian',
  russian = 'russian',
}

export const ElevenLabsSupportedLanguagesArray = Object.keys(
  ElevenLabsSupportedLanguages,
);
