export enum ResourceType {
  Message = 'Message',
  MessageLabelAdded = 'MessageLabelAdded',
  Channel = 'Channel',
  ChannelUsersAdded = 'ChannelUsersAdded',
  ChannelUserJoined = 'ChannelUserJoined',
  ChannelUserRemoved = 'ChannelUserRemoved',
  ChannelUserLeft = 'ChannelUserLeft',
  Workspace = 'Workspace',
  WorkspaceUserJoined = 'WorkspaceUserJoined',
  WorkspaceUserAdded = 'WorkspaceUserAdded',
  WorkspaceUserRemoved = 'WorkspaceUserRemoved',
  WorkspaceUserLeft = 'WorkspaceUserLeft',
  WorkspaceFindableChannelCreated = 'WorkspaceFindableChannelCreated',
  AIPromptResponseGenerated = 'AIPromptResponseGenerated',
  WorkspaceLevelAIPromptResponseGenerated = 'WorkspaceLevelAIPromptResponseGenerated',
  WorkspaceLevelMessageLabelAdded = 'WorkspaceLevelMessageLabelAdded',
}
